namePrefix: production-
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
labels:
- includeSelectors: true
  pairs:
    variant: production
patches:
- path: prod-patches.yaml
images:
- name: mashabrauer/pastr
  newTag: bea4c1b
